export interface Question {
  // server side
  id: string; // Unique identifier for each question, generated by the system.
  isReviewed: string; // Tracks whether the question has been reviewed (e.g., 'yes', 'no').
  reviewedBy: string; // The name or ID of the person who reviewed the question. by defeult it will system
  lastUpdated: string; // Timestamp of the last update, for tracking changes.
  selectionCount?: number; // Tracks how many times the question has been used or selected. by defeult it will 0

  // client side
  class: number; // The class/grade level of the question (e.g., 1 to 10).
  subject: string; // The subject of the question (e.g., Math, Science).
  bookName: string; // Name of the textbook associated with the question.
  board: string; // Educational board (e.g., CBSE, GSEB).
  Ch: string; // Chapter number.
  chapterName: string; // Full name of the chapter.
  section: string; // Section within the chapter (if applicable).
  type: string; // Type of question (e.g., 'MCQ', 'Short Answer').
  question: string; // The text of the question.
  questionImages: string[]; // URLs or paths for question-related images.
  question_images?: string[]; // Optional for backward compatibility.
  answer: string | string[] | Record<string, string | string[]>; // Answer(s) for the question.
  answerImages?: string[]; // Optional: URLs or paths for answer-related images.
  answer_images?: string[]; // Optional for backward compatibility.
  options?: Record<string, string>; // For MCQs, key-value pairs of options.
  marks: number; // Marks allocated to the question.
}
export interface SubjectData {
  class: number;
  board: string;
  medium?: string;
  subject?: string;
  subjects?: Array<{
    name: string;
    mediums?: Array<{
      language: string;
    }>;
  }>;
}

export interface Section {
  type: string;
  questions: Question[];
}

export interface Chapter {
  id: string;
  name: string;
  Ch: string;
  class: number;
  board: string;
  subject: string;
  questions: Question[];
}

interface Subject {
  name: string;
  mediums?: { language: string }[];
}

export interface SubjectDataItem {
  medium?: string;
  class: number;
  board: string;
  subject?: string;
  subjects?: Subject[];
}

export interface SubjectSelectorProps {
  subjectData: SubjectDataItem[];
  classNumber: number;
  board: string;
  medium: string;
  onSelectSubject: (subject: string) => void;
  initialSubject: string | null;
}

export interface ChapterSelectorProps {
  questionBankData: Chapter[];
  onSelectQuestions: (questions: Question[]) => void;
}

export interface ExamMetadata {
  instituteName: string;
  standard: number | null;
  subject: string | null;
  chapters: string[];
  studentName?: string;
  teacherName: string;
  totalMarks: number;
}
export interface GeneratedExamProps extends ExamMetadata {
  selectedQuestions: Question[];
}

export interface PdfDownloadProps extends ExamMetadata {
  selectedQuestions: Question[];
  contentId?: string; // Add this if necessary
}

export interface SelectedChapter {
  id: string;
  name: string;
}

export interface ClassSelectorProps {
  subjectData: any[];
  onSelectClass: (classNumber: number) => void;
  onSelectBoard: (board: string) => void;
  onSelectMedium: (medium: string) => void;
  initialClass: number | null;
  initialBoard: string | null;
  initialMedium: string | null;
}
