import React from "react";

type Props = {
  userPaperCount: number;
  user: string;
};

const Footer = (props: Props) => {
  return (
    <>
      <div className="mt-4 text-center"></div>
      {/* <p>
        Total papers generated by {user}: {userPaperCount}
      </p> */}
      <footer className="mt-8 flex justify-between text-sm text-gray-500">
        <p>Created by Akshay</p>
        <p>App Version: 1.0.0-dev</p>
      </footer>
    </>
  );
};

export default Footer;
